[build-system]
  requires = ["setuptools"]
  build-backend = "setuptools.build_meta"

[project]
  name = "penelope-OSCP-safe"
  version = "0.14.8"
  requires-python = ">=3.6"

[project.scripts]
  penelope = "penelope-OSCP-safe:main"

[tool.setuptools]
  script-files = ["penelope-OSCP-safe.py"]
