[build-system]
  requires = ["setuptools"]
  build-backend = "setuptools.build_meta"

[project]
  name = "penelopeOSCPsafe"
  version = "0.14.14"
  requires-python = ">=3.6"

[project.scripts]
  penelopeOSCPsafe = "penelopeOSCPsafe:main"

[tool.setuptools]
  script-files = ["penelopeOSCPsafe.py"]
